#version=RHEL9
# Fedora Linux — Unattended Installation
# Generated by fedora-install/lib/xml2ks.py
# !! Do not edit by hand — regenerate from XML config !!

text
reboot

# ── Lokales RPM-Repo auf Ventoy-USB ──────────────────────────────────────────
repo --name=fedora-autoinstall --baseurl=file:///run/install/repo/rpm

%pre
#!/bin/bash
DISK=$(grep -oP '(?<=inst\.disk=)\S+' /proc/cmdline || true)
if [[ -z "$DISK" ]]; then
    DISK=$(lsblk -bdno NAME,TYPE,TRAN,RM,SIZE \
        | awk '$2=="disk" && $3!="usb" && $4=="0" && $1!~/^zram/ {print $5+0, $1}' \
        | sort -rn | head -1 | awk '{print $2}')
fi
[[ -z "$DISK" ]] && { echo "ERROR: Keine Installations-Disk gefunden" >&2; exit 1; }
echo "Ziel-Disk: $DISK" >&2
cat > /tmp/disk-setup.cfg <<DEOF
ignoredisk --only-use=$DISK
zerombr
clearpart --all --initlabel --drives=$DISK
bootloader --boot-drive=$DISK
part /boot/efi --fstype=efi  --size=512
part /boot     --fstype=ext4 --size=1024
part btrfs.01  --fstype=btrfs --grow
btrfs none  --label=fedora btrfs.01
btrfs /     --subvol --name=@ LABEL=fedora
btrfs /home --subvol --name=@home LABEL=fedora
DEOF
%end

# ── Locale / keyboard / timezone ─────────────────────────────────────────────
keyboard --xlayouts='de'
lang de_DE.UTF-8
timezone Europe/Berlin --utc

# ── Firewall ──────────────────────────────────────────────────────────────────
firewall --enabled --service=ssh

# ── Network ───────────────────────────────────────────────────────────────────
network --bootproto=dhcp --device=link --activate
network --hostname=fedora-workstation

# ── Disk / partitioning ───────────────────────────────────────────────────────
%include /tmp/disk-setup.cfg

# ── Authentication ────────────────────────────────────────────────────────────
rootpw --lock
user --groups=wheel,video,audio --name=sija --password=$6$vIQuz3HLrh0EkSj6$KmIvhP/zN/NQfwRAiSOyl0H8mGmwrOYtwJXk0cBM98eONcgTU867DeR8NWIeRYJwGYQVCBxlkb2Sxt4dDfMKY. --iscrypted --gecos="sija"

# ── Packages ──────────────────────────────────────────────────────────────────
%packages
@^workstation-product-environment
git
curl
python3
python3-pip
python3-virtualenv
gnome-shell-extension-user-theme
gnome-shell-extension-dash-to-panel
flatpak
make
gcc
gcc-c++
cmake
openssh-server
ninja-build
fedora-autoinstall
%end

# ── %addon kdump ──────────────────────────────────────────────────────────────
%addon com_redhat_kdump --disable
%end

# ── %post: Env-Datei, Autostart ──────────────────────────────────────────────
%post --log=/root/ks-post.log

set -euo pipefail

# ── SSH aktivieren ────────────────────────────────────────────────────────────
systemctl enable sshd.service

# ── Write provisioning environment ───────────────────────────────────────────
cat > /etc/fedora-provision.env <<'ENVEOF'
FEDORA_TARGET_USER="sija"
FEDORA_KERNEL_SOURCE="cachyos"
FEDORA_CUDA_SOURCE="nvidia"
FEDORA_VLLM_CUDA_VERSION="13.2"
FEDORA_VLLM_ARCH_LIST="12.0"
FEDORA_VLLM_ROUTER_PORT="8000"
FEDORA_VLLM_REGISTRY="~/.config/vllm-router/models.json"
FEDORA_AGENT_MODEL="Qwen/Qwen3-14B-AWQ"
FEDORA_AUDIO_MODEL="moonshotai/Kimi-Audio-7B-Instruct"
FEDORA_PYTORCH_VENV="~/.venvs/ai"
FEDORA_VLLM_VENV="~/.venvs/bitwig-omni"
FEDORA_AUDIO_VENV="~/.venvs/kimi-audio"
FEDORA_WS_GTK_ARGS="-c Dark"
FEDORA_WS_ICON_ARGS="-dark"
FEDORA_WS_WALL_ARGS=""
FEDORA_OMB_THEME="modern"
FEDORA_NEO4J_URI="bolt://localhost:7687"
FEDORA_NEO4J_USER="neo4j"
FEDORA_NEO4J_PASSWORD="bitwig-agent"
ENVEOF
chmod 0644 /etc/fedora-provision.env

# ── Flathub einrichten ────────────────────────────────────────────────────────
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo 2>/dev/null || true

# ── First-Login Autostart für Ziel-User ──────────────────────────────────────
USER_HOME="/home/sija"
AUTOSTART_DIR="$USER_HOME/.config/autostart"
mkdir -p "$AUTOSTART_DIR"
cat > "$AUTOSTART_DIR/fedora-first-login.desktop" <<'DESKTOPEOF'
[Desktop Entry]
Type=Application
Name=Fedora First-Login Setup
Exec=/usr/local/bin/fedora-first-login.sh
Hidden=false
NoDisplay=true
X-GNOME-Autostart-enabled=true
DESKTOPEOF
chown -R sija:sija "$USER_HOME/.config"

%end
